### ISSUE TITLE
Calling the external functions with nonce = 0 does not have desired effect

### ISSUE THREAD

**Issue by jgostylo** [dmihal/eth-permit#13]
The edge case where setting nonce=0 currently does not override the function to query the contract for the nonce.

This is actually an extremely important edge case as it is the first nonce that you must use for DAI.  There is no way that I can see to work around this limitation to interact with a pre-fork deployment of the DAI contract on a test chain fork like what you get with hardhat.

**Comment by dmihal** [comment]
Closed in #14
